#### Recuperar todas las peliculas
GET  https://elibro.net/api/notes/?user_id=7181816&book_id=70431
#### Recuperar todas las peliculas
GET  http://localhost:3000/sunat-api?id=44a6b789-9b52-44e3-aaf9-ba9efd96e2c2&clave=qg2q9lUXfI7fvesWej3J9g==


user_id=7181816&book_id=70431

#### Recuperar una pelicula por id
GET http://localhost:3000/movies/f4aea1ea-ad19-4363-9a83-a7afc09500ee
#### Recuperar todas las peliculas por género
GET http://localhost:3000/movies

#### Crear una película con POST
POST https://sunat-api-facturacion-dev-bsda.2.us-1.fl0.io/sunat-api
Content-Type: application/json   

{
  "grant_type": "client_credentials",
  "scope": "https://api.sunat.gob.pe/v1/contribuyente/contribuyentes",
  "client_id": "44a6b789-9b52-44e3-aaf9-ba9efd96e2c2",
  "client_secret": "qg2q9lUXfI7fvesWej3J9g=="
}
#### Crear una película con POST
POST http://localhost:3000/sunat-api
Content-Type: application/json   

{
  "grant_type": "client_credentials",
  "scope": "https://api.sunat.gob.pe/v1/contribuyente/contribuyentes",
  "client_id": "44a6b789-9b52-44e3-aaf9-ba9efd96e2c2",
  "client_secret": "qg2q9lUXfI7fvesWej3J9g=="
}

#### Actualizar una pelicula
PATCH http://localhost:3000/movies/f0bcd26e-941a-4d61-a38b-b851171ceeef
Content-Type: application/json

{
  
}

#### Delete
